# Generated by Django 5.0.14 on 2026-03-03 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя исполнителя')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('yandex_id', models.CharField(blank=True, max_length=100, verbose_name='ID Яндекс.Музыки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artists/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('release_type', models.CharField(choices=[('single', 'Сингл'), ('ep', 'EP'), ('album', 'Альбом')], default='album', max_length=10, verbose_name='Тип релиза')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='releases/', verbose_name='Обложка')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата релиза')),
                ('yandex_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Яндекс.Музыки')),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Средний балл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='catalog.artist', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Релиз',
                'verbose_name_plural': 'Релизы',
                'ordering': ['-created_at'],
            },
        ),
    ]
